export const newInvoiceHeadingTitle = "xpath=//span[@title='New Invoice' and text()='New Invoice']";
export const newInvoiceCustomerSearchBar = "xpath=//input[@type='search' and @role='combobox']";
export const saveAsDraftButton1 = "xpath=(//button[@type='button' and contains(@class, 'ant-btn')][span[text()='Save as draft']])[1]";
export const saveAsDraftButton2 = "xpath=(//button[@type='button' and contains(@class, 'ant-btn')][span[text()='Save as draft']])[2]";
export const customerName = "xpath=//div[contains(@class, 'ant-select-item-option-active') and @title='Karl To']";
export const customerName1 = "xpath=(//span[@class='ant-typography font-bold' and text()='Karl To'])[1]";
export const customerName2 = "xpath=(//span[@class='ant-typography font-bold' and text()='Karl To'])[2]"; 
export const custom = "//span[text()='Custom']";
export const DueOnReceipt = "//span[text()='Due on Receipt']";
export const NET7 = "//span[text()='NET 7']";
export const NET10 = "//span[text()='NET 10']";
export const NET15 = "//span[text()='NET 15']";
export const NET30 = "//span[text()='NET 30']";
export const NET60 = "//span[text()='NET 60']";
export const NET90 = "//span[text()='NET 90']";